development:
  adapter: sqlite3
  encoding: unicode
  database: development.sqlite3
  pool: 5

test:
  adapter: sqlite3
  encoding: unicode
  database: test.sqlite3
  pool: 5

production:
  adapter: sqlite3
  encoding: unicode
  database: test.sqlite3
  pool: 5

